### ISSUE TITLE
PHP 8.1 deprecation warnings

### ISSUE THREAD

**Issue by matjazpotocnik** [kixe/FormProcessor#1]
`PHP Deprecated: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in ...\wwwroot\site\modules\FormProcessor\FormProcessor.module:line 190 and 329`

**Comment by kixe** [comment]
@matjazpotocnik 
Currently I am working in a PHP 8.0 environment for dev. I tried to fix the bug. Please check. Tell me if you see any other Errors or Warnings in PHP 8.1

**Comment by matjazpotocnik** [comment]
did you commit the changes?
