### ISSUE TITLE
Issue with profile image/avatar

### ISSUE THREAD

**Issue by matjazpotocnik** [kixe/FormProcessor#2]
When accessing a poll (ProcessPolls) as a logged user (if that matters) eg. http://localhost/processwire/process_poll/participate/?id=xxxx&token=yyyyyy, this error/warning is shown:

```
Pageimage: Rename failed: .../wwwroot/site/assets/cache/WireTempDir/.PFM0.15002400T1645557532R5OPQKKM3BRoEZh/0/frog.60x60.jpg => frog.60x60.jpg
WireFileTools: rename: Rename to pathname ($newName) that already exists: .../wwwroot/site/assets/cache/WireTempDir/.PFM0.15002400T1645557532R5OPQKKM3BRoEZh/0/frog.60x60.jpg
```

frog.60x60.jpg is API resized frog.jpg - an avatar image set in the profile edit. When I comment this line:

`else $this->instance->addHookBefore('PagefilesManager::path', function ($e) {$e->replace = true;$e->return = null;});` in the ___render() method, the error goes away. Just to say, my poll/form template only contains a title (PageTitleLanguage) and a checkbox (Toggle).

**Comment by kixe** [comment]
@matjazpotocnik 
Fixed. Please check.
